[SheetConfig]
    name        = "Sheet1"
    name_col    = "C"
    phone_col   = "B"
    code_col    = "A"
    start_row   = 1

[[Seqs]]
    seq = "tab"
[[Seqs]]
    seq = "tab tab"
[[Seqs]]
    seq = "tab tab tab tab tab enter tab enter"