[SheetConfig]
    name        = "Sheet1"
    name_col    = "B"
    phone_col   = "C"
    code_col    = "A"
    start_row   = 1

[Command]
    number = 4

[[Seqs]]
    seq = "tab"
[[Seqs]]
    seq = "tab tab"
[[Seqs]]
    seq = "tab tab tab tab tab enter"
[[Seqs]]
    seq = "tab enter"